### ISSUE TITLE
TypeError: Cannot read property 'game_id' of undefined

### ISSUE THREAD

**Issue by JDittmerCOM** [destial/twitchrequest#2]
I get an error message when I execute this exact code from your documentation. 

```javascript
const TwitchClientOptions = {
    channels: ['dracon', 'nilson1489', 'einfachflow'],
    client_id: "xxxxxxxxxxxxxxxxxx",
    client_secret: "xxxxxxxxxxxxxxxxxx",
    interval: 60
};
const client = new Client(TwitchClientOptions);

client.on('live', (streamData) => {
	console.log(streamData);
})
```

```
TypeError: Cannot read property 'game_id' of undefined
    at Client.<anonymous> (/root/twitchStreamBot/node_modules/twitchrequest/index.js:81:119)
    at step (/root/twitchStreamBot/node_modules/twitchrequest/index.js:46:23)
    at Object.next (/root/twitchStreamBot/node_modules/twitchrequest/index.js:27:53)
    at fulfilled (/root/twitchStreamBot/node_modules/twitchrequest/index.js:18:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by cartiqo** [comment]
Bro really didn't get an answer
